language: rust
sudo: false
cache: cargo
env: RUN=TEST
rust:
- nightly
- beta
- stable
matrix:
  include:
  - rust: stable
    env: RUN=RUSTFMT
    before_script: rustup component add rustfmt
    script:
    - cargo check
    - cargo fmt --all -- --check
script:
- cargo build --verbose
- cargo test --verbose
